FROM pytorch/torchserve 

ARG MODEL_NAME
ARG MODEL_FILE
ARG MODEL_WEIGHTS
ARG CONFIG_FILE
ARG EXTRA_FILES

USER root

WORKDIR /app

COPY requirements.txt .

RUN apt-get update -y && apt-get install -y curl

RUN pip install -r requirements.txt

COPY . .

RUN mkdir model_store && \
    torch-model-archiver \
    --model-name $MODEL_NAME \
    --version 1.0 \
    --model-file $MODEL_FILE \
    --serialized-file $MODEL_WEIGHTS \
    --handler handlers/object_handler.py \
    --export-path model_store \
    --extra-files backbone/modules.py,classifier/NConvMDense.py,$CONFIG_FILE,$EXTRA_FILES

ENV MODEL_NAME ${MODEL_NAME}

CMD "torchserve --start --model-store model_store --models ${MODEL_NAME}=${MODEL_NAME}.mar --ts-config properties/config.properties"